"""
Report Generator — Structured medical report output.
ChatGPT-quality formatting with audience-aware styling.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generates structured medical reports.

    Output format:
        🧠 Diagnosis
        📊 Confidence
        📚 Evidence
        🧪 Recommended Tests
        💊 Treatment Options
        ⚠️ Risk Level
        👨‍⚕️ Doctor Advice
    """

    REPORT_TEMPLATE = """
╔══════════════════════════════════════════════════════════════╗
║               🏥 MEDICAL ANALYSIS REPORT                     ║
╚══════════════════════════════════════════════════════════════╝

📋 Report ID: {report_id}
📅 Generated: {timestamp}
🤖 Engine: Medical LLM Super-Engine v1.0
👤 Mode: {mode}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🧠 DIAGNOSIS & ASSESSMENT
{diagnosis}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📊 CONFIDENCE & UNCERTAINTY
• Overall Confidence: {confidence}%
• Model Agreement: {agreement}%
• Uncertainty Level: {uncertainty}
{uncertainty_detail}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📚 SUPPORTING EVIDENCE
{evidence}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🧪 RECOMMENDED TESTS & INVESTIGATIONS
{tests}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

💊 TREATMENT OPTIONS
{treatment}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

⚠️ RISK ASSESSMENT
• Risk Level: {risk_level}
{risk_details}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👨‍⚕️ CLINICAL RECOMMENDATIONS
{recommendations}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🔬 MODELS USED
{models_used}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🔗 CITATIONS
{citations}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

⚕️ SAFETY VALIDATION
{safety_status}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📌 DISCLAIMER: This analysis is generated by an AI system and
   is intended for informational purposes only. It should NOT
   be used as a substitute for professional medical advice,
   diagnosis, or treatment. Always consult a qualified
   healthcare provider for medical decisions.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

    def generate(
        self,
        fused_result: dict[str, Any],
        safety_result: dict[str, Any] | None = None,
        rag_evidence: list[dict[str, Any]] | None = None,
        drug_check: dict[str, Any] | None = None,
        mode: str = "doctor",
        report_id: str = "",
        sources: list[dict[str, Any]] | None = None,
    ) -> dict[str, Any]:
        """Generate a structured medical report.

        Args:
            fused_result: Output from MetaFusion
            safety_result: Safety validation results
            rag_evidence: RAG retrieved evidence
            drug_check: Drug interaction check results
            mode: Audience mode (doctor/patient/research)
            report_id: Report identifier

        Returns:
            Structured report dict with text and sections
        """
        consensus = fused_result.get("consensus_answer", fused_result.get("text", ""))
        confidence = fused_result.get("confidence", 0)
        agreement = fused_result.get("agreement_score", 0)

        # Parse sections from consensus text
        sections = self._parse_sections(consensus)

        # Format evidence
        evidence_text = self._format_evidence(rag_evidence)
        citations_text = self._format_citations(sources, rag_evidence)

        # Format models used
        individual = fused_result.get("individual_results", [])
        models_text = "\n".join(
            f"• {r.get('model', 'Unknown')} (role: {r.get('role', 'primary')}, "
            f"score: {r.get('score', 0):.3f})"
            for r in individual
        ) or "• No model details available"

        # Risk assessment
        risk_result = safety_result or {}
        risk_level = risk_result.get("risk_level", "unknown")
        risk_details = ""
        flagged = risk_result.get("flagged_findings", [])
        if flagged:
            risk_details = "\n".join(f"  ⚠ {f['finding']} ({f['risk_level']})" for f in flagged)

        # Safety status
        safety_status = "✅ Validated" if risk_result.get("is_valid", True) else "⚠️ Review Required"
        safety_warnings = risk_result.get("warnings", [])
        if safety_warnings:
            safety_status += "\n" + "\n".join(f"  ⚠ {w}" for w in safety_warnings[:5])

        # Drug interactions
        if drug_check and drug_check.get("has_interactions"):
            for inter in drug_check.get("interactions", []):
                risk_details += (
                    f"\n  💊 Drug Interaction: {inter.get('drug_1')} + {inter.get('drug_2')} "
                    f"({inter.get('severity')}) — {inter.get('effect')}"
                )

        # Uncertainty detail
        uncertainty_detail = ""
        if fused_result.get("contradictions"):
            contradictions = fused_result["contradictions"]
            if contradictions.get("has_contradictions"):
                uncertainty_detail = (
                    f"  ⚠ {contradictions.get('count', 0)} contradiction(s) detected "
                    f"(severity: {contradictions.get('severity', 'unknown')})"
                )

        # Format the report
        report_text = self.REPORT_TEMPLATE.format(
            report_id=report_id or "auto",
            timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
            mode=mode.capitalize(),
            diagnosis=sections.get("diagnosis", consensus[:1000]),
            confidence=f"{confidence * 100:.1f}",
            agreement=f"{agreement * 100:.1f}",
            uncertainty=self._uncertainty_label(1.0 - agreement),
            uncertainty_detail=uncertainty_detail,
            evidence=evidence_text or "No specific evidence retrieved.",
            tests=sections.get("tests", "See diagnosis section for recommended workup."),
            treatment=sections.get("treatment", "See clinical recommendations."),
            risk_level=risk_level.upper(),
            risk_details=risk_details or "  No critical findings flagged.",
            recommendations=sections.get("recommendations", "Consult with a healthcare provider for personalized advice."),
            models_used=models_text,
            citations=citations_text,
            safety_status=safety_status,
        )

        return {
            "report_text": report_text,
            "sections": sections,
            "metadata": {
                "report_id": report_id,
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "mode": mode,
                "confidence": confidence,
                "agreement": agreement,
                "risk_level": risk_level,
                "models_used": [r.get("model") for r in individual],
                "source_count": len(sources or []),
            },
        }

    def _parse_sections(self, text: str) -> dict[str, str]:
        """Parse model output into report sections."""
        sections: dict[str, str] = {}
        current_key = "diagnosis"
        current_lines: list[str] = []

        section_markers = {
            "diagnosis": ["diagnosis", "assessment", "clinical assessment", "impression", "primary diagnosis"],
            "differential": ["differential", "possible diagnoses", "possibilities"],
            "tests": ["test", "investigation", "workup", "lab", "imaging", "recommended test"],
            "treatment": ["treatment", "management", "therapy", "medication", "drug", "prescription"],
            "recommendations": ["recommend", "follow-up", "next step", "plan", "advice"],
            "evidence": ["evidence", "reference", "literature", "supporting"],
        }

        for line in text.split("\n"):
            line_lower = line.strip().lower()

            matched = False
            for key, markers in section_markers.items():
                if any(m in line_lower for m in markers) and len(line.strip()) < 100:
                    # Save previous section
                    if current_lines:
                        sections[current_key] = "\n".join(current_lines).strip()
                    current_key = key
                    current_lines = []
                    matched = True
                    break

            if not matched:
                current_lines.append(line)

        # Save last section
        if current_lines:
            sections[current_key] = "\n".join(current_lines).strip()

        return sections

    def _format_evidence(self, rag_evidence: list[dict[str, Any]] | None) -> str:
        """Format RAG evidence for the report."""
        if not rag_evidence:
            return ""

        parts = []
        for i, ev in enumerate(rag_evidence[:5], 1):
            source = ev.get("metadata", {}).get("source", "Unknown")
            relevance = ev.get("relevance", 0)
            content = ev.get("content", "")[:200]
            parts.append(
                f"[{i}] (relevance: {relevance:.3f}) {source}\n"
                f"    {content}"
            )

        return "\n\n".join(parts)

    def _format_citations(
        self,
        sources: list[dict[str, Any]] | None,
        rag_evidence: list[dict[str, Any]] | None,
    ) -> str:
        if sources:
            parts = []
            for i, source in enumerate(sources[:6], 1):
                title = source.get("title", "Untitled source")
                label = source.get("source") or source.get("domain") or source.get("type", "source")
                url = source.get("url") or "N/A"
                confidence = source.get("confidence")
                if confidence is not None:
                    parts.append(
                        f"[{i}] {title} ({label}, confidence {float(confidence):.2f})\n    {url}",
                    )
                else:
                    parts.append(f"[{i}] {title} ({label})\n    {url}")
            return "\n\n".join(parts)

        if rag_evidence:
            parts = []
            for i, ev in enumerate(rag_evidence[:5], 1):
                source = ev.get("metadata", {}).get("source", "Unknown")
                parts.append(f"[{i}] {source}")
            return "\n".join(parts)

        return "No external citations available."

    def _uncertainty_label(self, uncertainty: float) -> str:
        if uncertainty < 0.2:
            return "🟢 LOW — High confidence"
        elif uncertainty < 0.4:
            return "🟡 MODERATE — Minor model disagreement"
        elif uncertainty < 0.6:
            return "🟠 ELEVATED — Consider expert review"
        return "🔴 HIGH — Significant disagreement, expert review required"


class ResponseStyler:
    """Audience-aware response formatting.

    Modes:
    - doctor: Technical, guideline-referenced
    - patient: Simple, empathetic, no jargon
    - research: Cited, evidence-focused
    """

    STYLE_INSTRUCTIONS = {
        "doctor": (
            "Present this information in a professional clinical format suitable "
            "for a physician. Use standard medical terminology. Reference guidelines "
            "and classification systems where applicable. Be concise and systematic."
        ),
        "patient": (
            "Rewrite this information for a patient to understand. Use simple, "
            "everyday language. Explain medical terms when you must use them. "
            "Be empathetic and reassuring while remaining accurate. "
            "Use bullet points for clarity."
        ),
        "research": (
            "Present this information in an academic/research format. "
            "Include citations where possible. Discuss evidence quality. "
            "Note limitations and areas of uncertainty. Use formal academic tone."
        ),
    }

    def style(
        self,
        report_text: str,
        mode: str = "doctor",
    ) -> str:
        """Apply audience-appropriate styling to a report.

        For now, returns the report with mode-appropriate framing.
        In production, this would use a lightweight model to restyle.

        Args:
            report_text: Raw report text
            mode: Target audience

        Returns:
            Styled report text
        """
        prefix = self._get_mode_prefix(mode)
        disclaimer = self._get_disclaimer(mode)

        return f"{prefix}\n\n{report_text}\n\n{disclaimer}"

    def _get_mode_prefix(self, mode: str) -> str:
        prefixes = {
            "doctor": "📋 Clinical Report — For Healthcare Professional Review",
            "patient": "💬 Your Health Summary — Explained in Simple Terms",
            "research": "📄 Evidence-Based Analysis Report",
        }
        return prefixes.get(mode, prefixes["doctor"])

    def _get_disclaimer(self, mode: str) -> str:
        disclaimers = {
            "doctor": (
                "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                "Clinical Decision Support — Not a definitive diagnosis.\n"
                "Clinical correlation and professional judgment required."
            ),
            "patient": (
                "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                "🙏 Remember: This information is meant to help you understand\n"
                "your health better, but it's NOT a replacement for seeing your\n"
                "doctor. Please discuss these findings with your healthcare provider."
            ),
            "research": (
                "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
                "Note: This analysis is AI-generated and should be validated\n"
                "against primary literature. Evidence quality assessments are\n"
                "approximate and may not reflect formal GRADE evaluation."
            ),
        }
        return disclaimers.get(mode, disclaimers["doctor"])
